name: career-trends-analyzer
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - imbalanced-learn
  - stable-baselines3
  - gymnasium
  - jupyter
  - pip
  - nltk
  - tqdm
  - black
  - flake8
  - nbqa
  - pip:
      - gymnasium[classic_control]
